import type { NextPage } from 'next';
import Head from 'next/head';

import Flow from '../components/Flow';

import axios from 'axios'

import https from 'https'

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { data } = axios.get('https://211.206.251.66:7000/Notice')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>React Flow - Next.js Example</header>
      <Flow />
    </div>
  );
};

export default Home;