import type { NextPage } from 'next';
import Head from 'next/head';


import styles from '../styles/Home.module.css';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Bar } from 'react-chartjs-2';

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend
);

export const options = {
  plugins: {
    title: {
      display: true,
      text: 'Chart.js Bar Chart - Stacked',
    },
  },
  scales: {
    x: {
      stacked: false,
    },
    y: {
      stacked: false,
      ticks: {
        stepSize: 20,
        min: 0,
        max: 100,
        callback: function(value) {
          return value + "%"
        }
      },
      afterDataLimits: (scale) => {
        scale.max = 100;
      },
      title: {
        display: true,
        align: 'end',
        color: '#808080',
        text: '비율: %'
      }
    },
  },
};

const labels = ['10세', '20세', '30세', '40세', '50세', '60세', '70세', '80세', '90세', '100세'];

export const data = {
  labels,
  datasets: [
    {
      label: '여성',
      data: [10, 20, 30, 40, 15],
      backgroundColor: 'rgb(255, 99, 132)',
    },
    {
      label: '남성',
      data: [1, 20, 30, 40, 50],
      backgroundColor: 'rgb(75, 192, 192)',
    },
  ],
};

const Home: NextPage = () => {
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Bar options={options} data={data} width="700px" height="320px" />
    </div>
  );
};

export default Home;